# Generated by Django 5.0.7 on 2024-07-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("vil", "Villa"),
                            ("apt", "Appartement"),
                            ("sto", "Magasin"),
                        ],
                        max_length=3,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                (
                    "photo",
                    models.ImageField(default="default.png", upload_to="properties/"),
                ),
                ("bathrooms", models.PositiveSmallIntegerField()),
                ("rooms", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="owners.owner"
                    ),
                ),
            ],
        ),
    ]
